### PR TITLE
add fht

### PR DESCRIPTION
**Pull request by With-Sky**
Add FHT algorithm to speed up square and multiplication.

### CODE REVIEW

**Comment by Twilight-Dream-Of-Magic** [comment]
You write the comment a bit more, and then it's better to write it in English.
Then you write `FHT_LIMIT = 50` a bit too small.
Because that's not a bit, it's a digit count.
That's the number of 64 bit blocks that store the blocks that are currently set to the 32 bit range.

Thanks for contributing the code.

---

你把注释写多一点，然后最好写英文的。
然后就是你写`FHT_LIMIT = 50`有点太小了。
因为那个不是比特，而是digit count。
也就是64的比特块，存储目前设置为32比特范围的块的数量。

感谢贡献代码。

**Comment by Twilight-Dream-Of-Magic** [comment]
I can't understand your optimized Fast Hartley Transform algorithm, please write some English comments and resource links in the key lines, if you don't, it will be unintelligible to others contributing code to this project in the future.

Then you Forked the modified version in my project
Please submit it again after you pass the unit tests on your own.

Thanks for contributing the code.

---

我看不懂你优化的快速哈特利变换算法，麻烦你在关键的行写点英文注释和资源链接，如果你不这么做，以后这个项目别人贡献代码的时候会看不懂。

然后你在Fork了我的项目中的修改版本
请您自行通过单元测试之后再次提交。

感谢贡献代码。

**Comment by With-Sky** [comment]
我认为这种算法理解其数学原理的话理解起代码来很快，不理解数学的话注释写再多也无济于事，我放了两篇关于FHT的文章以及一篇关于模板递归优化性能的文章，但是注释我不认为还有加的必要。

**Comment by Twilight-Dream-Of-Magic** [comment]
Ok, thanks for your cooperation, your code I have merged

---

好的，谢谢你的合作，你的代码我已经merged

**Pull request merged**
